### ISSUE TITLE
In some cases the API doesn't start 

### ISSUE THREAD

**Issue by vejmarie** [RuggedPOD/ruggedpod-api#26]
It looks like that i2c address are the root cause of this issue. We need to have a stronger device discovery mechanism, as to ensure that the API start or report something that a human can understand !

**Edited (by ggiamarchi on Thu Aug  4 14:13:31 CEST 2016)**

To do list for this issue :
- [x] Don't fail the server startup on an I2C issue
- [x] Add a management API for I2C configuration
- [ ] ~~Implement auto-detection for I2C device ?~~

**Comment by ggiamarchi** [comment]
Currently, I2C addresses are stored in the yaml configuration. It would be more convenient to see and manage this configuration throw the web console. Even if this configuration should be done only once at the initial setup it can be useful in some unexpected circumstances.

In any case, an I2C configuration problem should never be a problem for the API server to start
